name: Build standard image

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - id: get_version
      uses: battila7/get-version-action@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag no-ip-updater:${{ steps.get_version.outputs.version }}
